### PR TITLE
Update 1.5.0

### PR DESCRIPTION
**Pull request by soburi**
Update to version 1.5.0.

- src/rp2_common/hardware_pll/pll.c changed from 1.3.0 to 1.5.0
  added code to refer to `MHZ`. Modify it additionally.

- `irq_is_enabled()` that defined in irq.h of PICO-SDK conflicts with zephyr's API. 
   Rename it to avoid compile errors.

---
I already made a PR for the update to 1.4.0 as #3, but 1.5.0 came out before it was merged, so I made a new PR. If there is no need to go via 1.4.0, I would like to proceed here.

### CODE REVIEW

**Comment by soburi** [comment]
@yonsch 
Could you take a look, please?
I'll abandon #3 that 1.4.0 update if no problem.

**Review by yonsch — APPROVED** [review]
Changes themselves look good, I'm never too sure if this should be performed with a merge or a rebase, I'll ask someone to take a look

**Comment by yonsch** [comment]
@soburi You can use the existing PR in Zephyr to point to this new PR. In any case, it needs to pass the CI before it can be merged here.

**Comment by soburi** [comment]
@yonsch 
> @soburi You can use the existing PR in Zephyr to point to this new PR. In any case, it needs to pass the CI before it can be merged here.

Thanks for notify.
Update done.

**Pull request merged**
