### PR TITLE
Update 2.0.0

### PR DESCRIPTION
**Pull request by soburi**
Update to version 2.0.0.

- Preventing the redefinition of `__weak.`
- Disabling sanity check the GPIO IRQ status

### CODE REVIEW

**Review by yonsch — APPROVED** [review]

**Comment by soburi** [comment]
@cfriedt @carlescufi 

I don't have merge permissions, so could you please merge as previous time?

**Comment by henrikbrixandersen** [comment]
"This branch cannot be rebased due to conflicts"?

**Comment by soburi** [comment]
@henrikbrixandersen 

I used the `merge` command to incorporate changes, so rebasing may result in complicated results.
Merge with `upstream/zephyr` produces the expected results,
so can you incorporate the changes with the `merge` command rather than `rebase`?

**Comment by soburi** [comment]
@cfriedt @carlescufi @henrikbrixandersen

The PR for Pico2 support https://github.com/zephyrproject-rtos/zephyr/pull/77368  is progressing,
and it will soon be necessary to merge this.
I do not have write permissions for this repositoy, so I would like you to do this.

As with past updates, the changes are being incorporated using merge, and a conflict would occur if you were to rebase.
I have confirmed that pull/6/head can be merged into main (`git merge pr6_fetched_branch`), so would it be possible to merge this using this method?

**Pull request merged**
