### PR TITLE
Adapting the hardware_timer API to Zephyr

### PR DESCRIPTION
**Pull request by soburi**
I created PR https://github.com/zephyrproject-rtos/zephyr/pull/57134 to support the rpi_pico timer feature.
This PR adapts pico-sdk's hardware_timer implementation for use with Zephyr.
Change the pico-sdk not to modify the interrupt vector because  Zephyr uses it.

### CODE REVIEW

**Comment by cfriedt** [comment]
@yonsch - please review
@soburi - if you find you are not getting reviews, you may need to tag the appropriate Zephyr Maintainer (via @ or on Discord)

**Comment by soburi** [comment]
@yonsch 
Could you take look at please?

**Review by yonsch — APPROVED** [review]

**Comment by soburi** [comment]
@carlescufi @cfriedt 
cc: @yonsch 

We have no permission to merge in this repository.
Could you do merge if there are no problem please?

**Comment by soburi** [comment]
@cfriedt Thank you!

**Pull request merged**
