### PR TITLE
Update 1.4.0

### PR DESCRIPTION
**Pull request by soburi**
Update to version 1.4.0.

- src/rp2_common/hardware_pll/pll.c changed from 1.3.0 to 1.4.0
  added code to refer to `MHZ`. Modify it additionally.

- `irq_is_enabled()` that defined in irq.h of PICO-SDK conflicts with zephyr's API. 
   Rename it to avoid compile errors.

### CODE REVIEW

**Review by yonsch — APPROVED** [review]

**Comment by yonsch** [comment]
@soburi Can you fix the merge conflict?

**Comment by soburi** [comment]
@yonsch 
I've already fixed the conflict caused by running `git merge 1.4.0`.
Is this answering the intention of your question?

**Comment by soburi** [comment]
little commit message updating.

**Comment by soburi** [comment]
@yonsch 
> @soburi Can you fix the merge conflict?

SnapCrab_Update 140 by soburi · Pull Request #3 · zephyrproject-rtoshal_rpi_pico — Mozilla Firefox_2023-1-27_7-2-34_No-00

I got this message. It seems cannot.

**Comment by soburi** [comment]
1.5.0 merged with #4.

**Pull request closed without merging**
